apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-svc
  namespace: roboshop
  labels:
    purpose: mongodb
    project: roboshop
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None
  selector:
    component: mongodb
    project: roboshop
    tier: database