apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: roboshop
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone : us-east-1c
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "redis-headless"  # headless service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: praneeth2701/redis:v2
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic-sc"   # here we used ebs dynamic
      resources:
        requests:
          storage: 2Gi